haproxy:
  image: eeacms/haproxy
  links:
  - webapp
  ports:
  - "3333:5000"
  - "1936:1936"
  environment:
  - SERVICE_NAMES=webapp
  - BACKENDS_PORT=80

webapp:
  image: 116.89.190.132:15000/se_gw
